PriceBotDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('PriceBotApi.urls')),
    path('promobot/', include('PromoBot.urls')),
    path('', include('priceBot.urls')),
]

PromoBot/urls.py
from django.urls import include, path
import PromoBot.views as views

from rest_framework import routers

app_name = 'promobot'

urlpatterns = [
    path('stores/', views.ListStores.as_view()),
    path('categories/<int:store_id>', views.ListCategories.as_view()),
    path('category-details/<int:store_id>/<int:category_id>',
         views.CategoryDetails.as_view()),
    path('products/<int:product_id>', views.Products.as_view()),
    path('products/', views.Products.as_view()),
    path('add-product-to-promo/', views.Promo.as_view()),


    #     path('get-category-url-and-products/<int:store_id>/<int:category_id>',
    #          views.get_category_url_and_products, name="get_category_url_and_products"),


    #     path('search-best-price', views.search_best_price, name="search_best_price"),
    #     path('add-product-to-promo/', views.add_product_to_promo,
    #          name="add_product_to_promo"),

    #     path('add-products/', views.add_products, name="promobot_add_products"),
    #     path('update/', views.update_product, name='update'),
    #     path('available_categories/<int:store_id>',
    path('available-categories/<int:store_id>', views.available_categories, name='available_categories'),
]

priceBot/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('rejestracja/', views.register_request, name="register"),
    path('logowanie/', views.login_request, name="login"),
    path('wyloguj/', views.logout_request, name="logout"),
    path('moje-konto/', views.user_page, name="user_page"),
    path('obslugiwane-sklepy/', views.available_stores, name="available_stores"),
    path('o-promobot/', views.about_page, name='about'),
    path('kontakt/', views.contact_page, name='contact'),
    path('zglos-blad/', views.report_bug_page, name='report_bug'),
    path('sledz-produkty/', views.add_products, name='add_products'),
    path('pobierz/', views.download, name='download'),
    path('szukaj/', views.search, name="search_product"),
    
    path('produkt/<int:product_id>', views.product, name='product'),
    
    path('edytuj-produkt/<int:product_id>', views.product_edit, name='product_edit'),
    path('edytuj-kategorie/<int:category_id>', views.category_edit, name='category_edit'),
    
    path('products-for-category/', views.products_for_category, name='products_for_category'),
    
    
    path('moje-konto/premium', views.premium, name='premium'),
    path('mojekonto/premium-ustawienia', views.premium_settings, name='premium_settings'),
    path('moje-konto/kategorie', views.categories_account, name='categories_account'),
    path('moje-konto/produkty', views.products_account, name='products_account'),
    path('moje-konto/twoje-dane', views.data_account, name='data_account'),
    path('moje-konto/usun', views.delete_account, name='delete_account'),
]

templates/app/about.html
{% extends 'app/base.html' %}

{% block title %}
  O PromoBot
{% endblock %}

{% block content %}
  <div class="box">
    <h1 class="title">O PromoBot</h1>
    <p>Promobot - [opis]</p>
    donate:
  </div>
{% endblock %}

templates/app/add_products.html
{% extends 'app/base.html' %}

{% block title %}
  Dodaj
{% endblock %}

{% block content %}
  <script>
    window.onload = function() {
    const nav_tabs = [document.querySelector("li#new"), document.querySelector("li#single-url"), document.querySelector("li#urls-from-file")];
    const tabs = document.querySelectorAll("div.tab");

    nav_tabs.forEach((nav_tab) => {
        nav_tab.addEventListener("click", () => {
          document.querySelector(".is-active").classList.remove("is-active");
          nav_tab.classList.add("is-active");

          switch (nav_tab.id) {
              case "new":
                  tabs.forEach((tab) => {
                      if (!tab.classList.contains("is-hidden")) {
                          tab.classList.add("is-hidden");
                      }
                  })
                  document.querySelector("div.tab.new").classList.remove("is-hidden");
                  break;
              case "single-url":
                  tabs.forEach((tab) => {
                      if (!tab.classList.contains("is-hidden")) {
                          tab.classList.add("is-hidden");
                      }
                  })
                  document.querySelector("div.tab.single-url").classList.remove("is-hidden");
                  break;
              case "urls-from-file":
                  tabs.forEach((tab) => {
                      if (!tab.classList.contains("is-hidden")) {
                          tab.classList.add("is-hidden");
                      }
                  })
                  document.querySelector("div.tab.urls-from-file").classList.remove("is-hidden");
                  break;

          }
      })
    })
  }
  </script>

  <h1 class="title">Dodaj produkty i adresy</h1>
  {{errors}}

  <div class="tabs">
    <ul><strong>Dodaj:</strong>
      <li id="new" class="is-active"><a>Nowy produkt</a></li>
      <li id="single-url"><a>Link dla istniejącego produktu</a></li>
      <li id="urls-from-file"><a>Linki z pliku dla istniejącego produktu</a></li>
    </ul>
  </div>

  <div class="block">

    <div class="tab new">
      <h1 class="title is-4">Nowy produkt</h1>

      <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="form-name" value="add-product">
        <div class="field has-addons">
          <p class="control is-one-third">
            <span class="select">
              <select name="category" required>
                <option disabled selected value>-- Wybierz kategorię --</option>
                {% for category in available_categories %}
                  <option value="{{ category.category_name }}">{{ category.category_name }}</option>
                {% endfor %}
              
              </select>
            </span>
          </p>
          <p class="control is-expanded">
            <input required name="product-name" class="input" type="text" placeholder="Nazwa produktu" maxlength="60">
          </p>
        </div>
        <p class="help">Brak kategorii? Dodaj ją w <a href="{% url 'main:user_page' %}">Moje konto</a></p>

        <hr>

        <h1 class="title is-4">Ustawienia produktu</h1>

        <div class="box has-background-white-ter">
          <h4 class="subtitle is-4">Pożądana cena</h4>

          <label for="" class="label">Cena</label>
          <div class="field">
            <div class="control">
              <input required name="wanted-price" class="input" type="number" placeholder="Cena w PLN" step="1">
            </div>
          </div>

          <label for="" class="label">Akceptowalne odstępstwo od pożądanej ceny</label>
          <p class="help">Przykład: gdy pożądna cena to 100zł, a odstępstwo wynosi 10%, dostaniesz powiadomienie gdy produkt osiągnie cenę 110zł</p>
          <div class="field">
            <div class="control">
              <input class="input" name="wanted-price-tolerancy" type="number" placeholder="Wartość w %" step="1" min="0" max="20">
            </div>
          </div>

          <label class="label">Gdzie chcesz otrzymywać powiadomienia:</label>
          <div class="field is-grouped">
            <div class="control">
              <label class="checkbox">
                <input name="main-notify" value="telegram" type="checkbox" checked>
                  Telegram
              </label>
            </div>
            <div class="control">
              <label class="checkbox">
                <input name="main-notify" value="email" type="checkbox">
                  E-mail
              </label>
            </div>
            <div class="control">
              <label class="checkbox">
                <input name="main-notify" value="sms" type="checkbox" disabled>
                  SMS (Wymaga konta premium)
              </label>
            </div>
            <div class="control">
              <label class="checkbox">
                <input name="main-notify" value="call" type="checkbox" disabled>
                  Połączenie telefoniczne (Wymaga konta premium)
              </label>
            </div>

          </div>

        </div>

        <div class="box has-background-white-ter">
          <h4 class="subtitle is-4">Powiadomienie o najniższych znalezionych cenach</h4>

          <label class="label">Wysyłaj powiadomienie co każde:</label>
          <div class="field is-grouped">
            <div class="control">
              <input name="lowest-price-notification-time-value" class="input" type="number" placeholder="Liczba godzin lub minut" value="24" step="1">
            </div>
            <div class="control">
              <div class="select">
                <select name="lowest-price-notification-time-unit">
                  <option value="h">Godziny</option>
                  <option value="m">Minuty</option>
                </select>
              </div>
            </div>
          </div>

          <label class="label">Gdzie chcesz otrzymywać powiadomienia:</label>
          <div class="field is-grouped">
            <div class="control">
              <label class="checkbox">
                <input name="lowest_price_notifty" value="telegram" type="checkbox" checked>
                  Telegram
              </label>
            </div>
            <div class="control">
              <label class="checkbox">
                <input name="lowest_price_notifty" value="email" type="checkbox">
                  E-mail
              </label>
            </div>
            <div class="control">
              <label class="checkbox">
                <input name="lowest_price_notifty" value="sms" type="checkbox" disabled>
                  SMS (Wymaga konta premium)
              </label>
            </div>
          </div>

        </div>
        <div class="has-text-centered">
          <button class="button is-primary is-fullwidth">Dodaj produkt</button>
        </div>
        
      </form>
    </div>

    <div class="tab single-url is-hidden">
      <div class="field has-addons">
        <p class="control is-one-third">
          <span class="select">
            <select>
              <option disabled selected>Wybierz kategorię</option>
              {% for category in available_categories %}
                <option value={{ category.category_name }}>{{ category.category_name }}</option>
              {% endfor %}
            </select>
          </span>
        </p>
        <p class="control is-one-third">
          <span class="select">
            <select>
              <option disabled selected>Wybierz produkt</option>
              <option>produkt2</option>
              <option>produkt3</option>
            </select>
          </span>
        </p>

        <p class="control is-expanded">
          <input class="input" type="text" placeholder="Tutaj wklej adres sklepu z twoim produktem">
        </p>
        <p class="control">
          <a class="button is-primary add-url">
            Dodaj adres
          </a>
        </p>
      </div>
    </div>

    <div class="tab urls-from-file is-hidden">
      urls from file
    </div>
    
  </div>

{% endblock %}

templates/app/available_stores.html
{% extends 'app/base.html' %}

{% block content %}


  <div class="is-flex is-justify-content-space-between">
    <h1 class="title">Obsługiwane sklepy</h1>
    <div class="field">
      <div class="control">
        <button class="button">Filtruj</button>
      </div>
    </div>

    <form action="" method="get">
      <div class="field is-grouped">
        <div class="control">
          <input name="search" class="input" type="text" placeholder="Szukaj...">
        </div>
        <div class="control">
          <input type="submit" class="button" value="Szukaj">
        </div>
      </div>
    </form>
  </div>

  <div class="tile is-ancestor is-flex-wrap-wrap">
    {% for store in stores %}
    <div class="tile is-parent is-3">
        <div class="tile is-child box has-text-centered">
          {% if store.is_premium %}<i title="Wymaga dostępu premium" class="fa-solid fa-star is-pulled-right" style="color: green;"></i>{% endif %}
          <p class="title">{{ store.name }} </p>
          <img src="{{ store.photo_url }}" alt="{{ store.name }} photo" width="140" >
        </div>
      </div>

    {% endfor %}
  </div>

{% endblock %}

templates/app/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <!-- TradeDoubler site verification 3269822 -->


  <title>
    {% block title %}{% endblock %}
  </title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  <script src="https://kit.fontawesome.com/4b8f99a165.js" crossorigin="anonymous"></script>
  <style>
    body {
        overflow: hidden;
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.8.2/dist/lazyload.min.js"></script>
</head>
<body class="is-dark has-background-dark is-fullheight-with-navbar" style="min-height: 100vh; height:100%">
  <nav class="navbar has-background-black-ter is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'main:homepage' %}">
        <strong class="title has-text-white">PromoBoss</strong>
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a href="{% url 'main:available_stores' %}" class="navbar-item">
          Obsługiwane sklepy
        </a>
        {% if user.is_authenticated %}
          <a href="{% url 'main:add_products' %}" class="navbar-item">
           Śledź własne produkty
          </a>
        {% endif %}

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Więcej
          </a>

          <div class="navbar-dropdown">
            <a href="{% url 'main:about' %}" class="navbar-item">
              O PromoBot
            </a>
            <a href="{% url 'main:contact' %}" class="navbar-item">
              Kontakt
            </a>
            <a href="{% url 'main:report_bug' %}" class="navbar-item">
              Zgłoś błąd
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item dark-mode-button"> Tryb ciemny</a>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <form action="{% url 'main:search_product' %}" method="get">
          <div class="field">
            <p class="control has-icons-left">
              <input class="input" name="search_term" type="text" placeholder="Wyszukaj produkt">
              <span class="icon is-small is-left">
                <i class="fa-solid fa-magnifying-glass"></i>
              </span>
            </p>
          </div>
        </form>
        </div>
        <div class="navbar-item">
          <div class="buttons">
            <a href="{% url 'main:download' %}" class="button is-white"><i class="fa-solid fa-download pr-2"></i>Pobierz</a>

            {% if user.is_authenticated %}
              <div class="has-dropdown is-hoverable navbar-item">
                <a href="{% url 'main:user_page' %}" class="button is-primary navbar-link">Moje konto</a>
              <div class="navbar-dropdown">
                <a href="{% url 'main:products_account' %}" class="navbar-item">
                  Produkty
                </a>
                <a href="{% url 'main:categories_account' %}" class="navbar-item">
                  Kategorie
                </a>
                <hr class="navbar-divider">
                <a href="{% url 'main:premium' %}" class="navbar-item has-text-success">
                  <strong>PREMIUM</strong>
                </a>
                <hr class="navbar-divider">
                <a href="{% url 'main:logout' %}" class="has-text-danger navbar-item">
                  Wyloguj
                </a>

              </div>
              </div>

            {% else %}
              <a href="{% url 'main:register' %}" class="button is-primary">
                <strong>Rejestracja</strong>
              </a>
              <a href="{% url 'main:login' %}" class="button is-light">
                Logowanie
              </a>
            {% endif %} 

          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="container mt-5 box">
    {% block content %}

    {% endblock %}
  </div>

  {% if messages %}
    <div class="columns is-justify-content-right is-fixed-top">

    {% for message in messages %}
      <div class="column notification is-info is-one-fifth mr-4 is-align-self-flex-end">
        <button class="delete"></button>
      {{ message }}
      </div>
    {% endfor %}
  </div>
  {% endif %}

  <script>
    document.addEventListener('DOMContentLoaded', () => {
    (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
      const $notification = $delete.parentNode;

      $delete.addEventListener('click', () => {
          $notification.parentNode.removeChild($notification);
        });
      });
      var lazyLoadInstance = new LazyLoad();      
    });

  
  </script>

</body>
</html>

templates/app/contact.html
{% extends 'app/base.html' %}

{% block title %}
  Kontakt
{% endblock %}

{% block content %}
  <div class="box">
    <h1 class="title">Kontakt</h1>
    [linki do kontaktu, email, github, linkedin]
  </div>
{% endblock %}

templates/app/download.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="title">Pobierz PromoBot</h1>
<div class="content has-text-centered">
    <div class="windows-mac-buttons">
        <a class="button is-primary is-large is-size-2">
            <p class="mb-1">
                <i class="fa-brands fa-windows pr-2"></i>Windows<br>
                <span class="help">Wspierane wersje: 10, 11</span>
            </p>
        </a>

        <a class="button is-primary is-large is-size-2">
            <span>
                <i class="fa-brands fa-apple pr-2"></i>Mac OS
            </span>
        </a>
            
    </div>
    <div class="other-links mt-3">
        <a class="is-size-5">Pozostałe <i class="fa-brands fa-linux"></i></a>
    </div>
</div>
<div class="content">
    <h2 class="subtitle">
        Instrukcje
    </h2>
</div>
{% endblock content %}

templates/app/homepage.html
{% extends 'app/base.html' %}

{% block content %}
  <script>
    window.onload = function() {
    const nav_tabs = [document.querySelector("li#hot"), document.querySelector("li#new"), document.querySelector("li#top")];
    const tabs = document.querySelectorAll("div.tab");

    nav_tabs.forEach((nav_tab) => {
        nav_tab.addEventListener("click", () => {
          document.querySelector(".is-active").classList.remove("is-active");
          nav_tab.classList.add("is-active");

          switch (nav_tab.id) {
              case "hot":
                  tabs.forEach((tab) => {
                      if (!tab.classList.contains("is-hidden")) {
                          tab.classList.add("is-hidden");
                      }
                  })
                  document.querySelector("div.tab.hot").classList.remove("is-hidden");
                  break;
              case "new":
                  tabs.forEach((tab) => {
                      if (!tab.classList.contains("is-hidden")) {
                          tab.classList.add("is-hidden");
                      }
                  })
                  document.querySelector("div.tab.new").classList.remove("is-hidden");
                  break;
              case "top":
                  tabs.forEach((tab) => {
                      if (!tab.classList.contains("is-hidden")) {
                          tab.classList.add("is-hidden");
                      }
                  })
                  document.querySelector("div.tab.top").classList.remove("is-hidden");
                  break;

          }
      })
    })
  }
  </script>

  <div class="tabs">
    <ul>
      <li id="hot"><a>Gorące</a></li>
      <li id="new" class="is-active"><a>Nowe</a></li>
      <li id="top"><a>TOP</a></li>
    </ul>
  </div>

  <div class="is-hidden hot block tab">
    <h1 class="title">Gorące okazje</h1>
    <div class="products is-flex is-flex-direction-column">
      <!-- CARD START-->
      {% for promo in promos %}
      <div class="card m-2">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-128x128">
                <img class="lazy" data-src="https://bulma.io/images/placeholders/128x128.png" alt="Placeholder image">
              </figure>
            </div>

              <div class="media-content">
                <p class="title is-3"><a href="">Nazwa produktu</a></p>
                <p class="subtitle is-6">[opis jakis ale skad w sumie]</p>

                <time datetime="1970-1-1">21:37 | 1. Stycznia 1970</time>
              </div>

              <div class="media-right">
                <div class="rating">
                  <i class="fa-solid fa-circle-plus" style="color: darkorange"></i>
                  2137
                  <i class="fa-solid fa-circle-minus" style="color: deepskyblue"></i>
                </div>
                <div class="comments has-text-right">
                  <i class="fa-solid fa-comments"></i> 0
                </div>
              </div>

          </div>

        </div>
      </div>
      {% endfor %}
      
      <!-- CARD END -->

    </div>

  </div>

  <div class="new block tab">
    <h1 class="title">Najnowsze okazje</h1>
    <div class="products is-flex is-flex-direction-column">
      <!-- CARD START-->
      {% for product in products %}
      <div class="card m-2">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-128x128">
                <img class="lazy" data-src="{{ product.thumbnail.img_url }}" alt="Placeholder image">
              </figure>
            </div>

              <div class="media-content">
                <p class="title is-3"><a href="">{{ product.name }}</a></p>
                <p class="subtitle is-6"><strong>{{ product.store_name }}</strong> | {{ product.category_name }}</p>

                <time datetime="1970-1-1">21:37 | 1. Stycznia 1970</time>
              </div>

              <div class="media-right">
                <div class="feedback is-justify-content-space-between">

                  <div class="rating">
                    <i class="fa-solid fa-circle-plus" style="color: darkorange"></i>
                    {{ votes }}
                    <i class="fa-solid fa-circle-minus" style="color: deepskyblue"></i>
                  </div>

                  <div class="comments">
                    <i class="fa-solid fa-comments"></i> 0
                  </div>

                </div>


                <div>
                  <s>{{ product.last_price }}</s>
                </div>
                <div>
                  <strong class="is-size-4">{{ product.price }}</strong>
                </div>
              </div>

          </div>

        </div>
      </div>
      {% endfor %}
    </div>

  </div>

  <div class="is-hidden top block tab">
    <h1 class="title">TOP okazje</h1>
    <p>Wybierz okres:</p>
    <div class="products is-flex is-flex-direction-column">
      <!-- CARD START-->
      <div class="card m-2">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-128x128">
                  <img class="lazy" data-src="https://bulma.io/images/placeholders/128x128.png" alt="Placeholder image">
                </figure>
              </div>

                <div class="media-content">
                  <p class="title is-3"><a href="">Nazwa produktu</a></p>
                  <p class="subtitle is-6">[opis jakis ale skad w sumie]</p>

                  <time datetime="1970-1-1">21:37 | 1. Stycznia 1970</time>
                </div>

                <div class="media-right">
                  <div class="rating">
                    <i class="fa-solid fa-circle-plus" style="color: darkorange"></i>
                    {{ votes }}
                    <i class="fa-solid fa-circle-minus" style="color: deepskyblue"></i>
                  </div>
                  <div class="comments has-text-right">
                    <i class="fa-solid fa-comments"></i> 0
                  </div>
                </div>

            </div>

          </div>
        </div>
      <!-- CARD END -->

      <div class="card m-2">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-128x128">
                  <img class="lazy" data-src="https://bulma.io/images/placeholders/128x128.png" alt="Placeholder image">
                </figure>
              </div>

                <div class="media-content">
                  <p class="title is-3"><a href="">Nazwa produktu</a></p>
                  <p class="subtitle is-6">[opis jakis ale skad w sumie]</p>

                  <time datetime="1970-1-1">21:37 | 1. Stycznia 1970</time>
                </div>

                <div class="media-right">
                  <div class="rating">
                    <i class="fa-solid fa-circle-plus" style="color: darkorange"></i>
                    {{ votes }}
                    <i class="fa-solid fa-circle-minus" style="color: deepskyblue"></i>
                  </div>
                  <div class="comments has-text-right">
                    <i class="fa-solid fa-comments"></i> 0
                  </div>
                </div>

            </div>

          </div>
        </div>
      <div class="card m-2">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-128x128">
                  <img class="lazy" data-src="https://bulma.io/images/placeholders/128x128.png" alt="Placeholder image">
                </figure>
              </div>

                <div class="media-content">
                  <p class="title is-3"><a href="">Nazwa produktu</a></p>
                  <p class="subtitle is-6">[opis jakis ale skad w sumie]</p>

                  <time datetime="1970-1-1">21:37 | 1. Stycznia 1970</time>
                </div>

                <div class="media-right">
                  <div class="rating">
                    <i class="fa-solid fa-circle-plus" style="color: darkorange"></i>
                    2137
                    <i class="fa-solid fa-circle-minus" style="color: deepskyblue"></i>
                  </div>
                  <div class="comments has-text-right">
                    <i class="fa-solid fa-comments"></i> 0
                  </div>
                </div>

            </div>

          </div>
        </div>
    </div>

  </div>

{% endblock %}

templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

  <div class="box">
    <form method="POST" class="p-5">
      <h1 class="title">Logowanie</h1>
    {% csrf_token %}
      <div class="is-danger">{{ login_form.non_field_errors }}</div>


    <div class="field">
      <div class="is-danger">{{ login_form.username.errors }}</div>
      <label class="label" for="{{ login_form.username.id_for_label }}">Nazwa użytkownika</label>
      <div class="control">
        {{ login_form.username }}
      </div>
    </div>

    <div class="field">
      <div class="is-danger">{{ login_form.password.errors }}</div>
      <label class="label" for="{{ login_form.password.id_for_label }}">Hasło</label>
      <div class="control">
        {{ login_form.password }}
      </div>
      <p class="help"><a href="{# Todo: forgot password #}">Nie pamiętasz hasła?</a></p>
    </div>

    <div class="field is-grouped">
    <div class="control">
      <input type="submit" class="button is-link" value="Zaloguj">
    </div>
    <div class="control">
      <a href="{% url 'main:homepage' %}" class="button is-link is-light">Anuluj</a>
    </div>
  </div>

    </form>
  </div>

{% endblock %}

templates/app/register.html
{% extends 'app/base.html' %}

{% block content %}

  <div class="box">
    <form method="POST" class="p-5">
      <h1 class="title">Rejestracja</h1>
    {% csrf_token %}
      <div class="is-danger">{{ register_form.non_field_errors }}</div>


    <div class="field">
      <div class="is-danger">{{ register_form.username.errors }}</div>
      <label class="label" for="{{ register_form.username.id_for_label }}">Nazwa użytkownika</label>
      <div class="control">
        {{ register_form.username }}
      </div>
    </div>

    <div class="field">
      <div class="is-danger">{{ register_form.email.errors }}</div>
      <label class="label" for="{{ register_form.email.id_for_label }}">Adres e-mail</label>
      <div class="control">
        {{ register_form.email }}
      </div>
    </div>

    <div class="field">
      <div class="is-danger">{{ register_form.password1.errors }}</div>
      <label class="label" for="{{ register_form.password1.id_for_label }}">Hasło</label>
      <div class="control">
        {{ register_form.password1 }}
      </div>
    </div>
    <div class="field">
      <div class="is-danger">{{ register_form.password2.errors }}</div>
      <label class="label" for="{{ register_form.password2.id_for_label }}">Powtórz hasło</label>
      <div class="control">
        {{ register_form.password2 }}
      </div>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <input type="submit" class="button is-link" value="Zarejestruj">
      </div>
      <div class="control">
        <a href="{% url 'main:homepage' %}" class="button is-link is-light">Anuluj</a>
      </div>
    </div>
      <p class="help">Masz już konto? <a href="{% url 'main:login' %}">Zaloguj się</a></p>

    </form>
  </div>

{% endblock %}

templates/app/report_bug.html
{% extends 'app/base.html' %}

{% block title %}
  Zgłoś błąd
{% endblock %}

{% block content %}
  <h1 class="title">Zgłoś błąd</h1>
  <div class="content">
    <p class="description">Znalazłeś na stronie lub w programie jakikolwiek błąd? Zgloś go przez poniższy formularz,
      a postaramy się jak najszybciej rozwiązać problem</p>
    <p class="info">Jeśli chcesz zostać poinformowany o naprawie problemu, zostaw swój adres e-mail.
      Damy znać, gdy problem zostanie rozwiązany!</p>

    <form action="POST">[formularz]</form>
  </div>
{% endblock %}